apiVersion: v2
name: kubeservice-ebpf-exporter
description: A Helm chart for ebpf_exporter
keywords:
- metric
- prometheus
- kubernetes
- ebpf
type: application
version: 1.2.1
appVersion: v2.3.0
home: https://github.com/kubeservice-stack/kubservice-charts
icon: https://kubeservice-stack.github.io/kubservice-charts/logo.png
sources:
- https://github.com/kubeservice-stack/ebpf_exporter
maintainers:
- name: dongjiang
  email: dongjiang1989@126.com
annotations:
  artifacthub.io/signKey: |
    fingerprint: 54145DF6791F044DDB2C9219F42BCA7408363131
    url: https://kubeservice-stack.github.io/kubservice-charts/pgp_keys.asc
  artifacthub.io/maintainers: |
    - name: dongjiang
      email: dongjiang1989@126.com
